### ISSUE TITLE
Artist not found in last.fm by musicbrainz id

### ISSUE THREAD

**Issue by cesalo** [jesseward/jellyfin-plugin-lastfm#3]
First of all thanks for taking the time to do this. I started using Jellyfin after years with Plex .. I used Emby for a while before sticking with Plex so I'm a bit familiar with the platform.
The first issue I had in terms of music was that the artist overview field was not being populated using musicbrainz or audiodb. After installing your plugin that apparently was fixed but after checking all the artists I found few that still had the overview section empty.
For what I see in the logs when I run a refresh metadata per artist is running:
http://ws.audioscrobbler.com/2.0/?method=artist.getInfo&mbid=e3d5b5ec-101a-4529-9f2d-01dca64cf44e
The issue is that it seems in last.fm few artists doesn't have the musicbrainz id registered so this fails with:
{"error":6,"message":"The artist you supplied could not be found","links":[]}
Is there a way to implement a second search like the one below when the first one fails or to choose which one to do:
http://ws.audioscrobbler.com/2.0/?method=artist.getInfo&artist=Anne-Marie
Using the name in this case it works. Not sure if this is something for the Jellyfin team or for  your plugin but it's worth a try.
Thanks.

**Comment by jesseward** [comment]
I don't plan on adding this any time soon in the plugin but had been thinking about this for other meta sources as well (such as Discogs or Spotify etc). LastFM was an easy integration, due to the core integration with MusicBrainz. 

As mentioned other types of meta sources, require further comparisons against artist/track (and potentially album name matching)
