### ISSUE TITLE
Question about how to update

### ISSUE THREAD

**Issue by cesalo** [jesseward/jellyfin-plugin-lastfm#8]
I see a couple of new releases (thanks). I'm running the docker version of Jellyfin, do I need to compile the dll or can I just grab the dll from the release section? I know I could try to do that either way but wanted to know the "official" way to do it.

**Comment by jesseward** [comment]
hey @cesalo due to licensing of this plugin, it cannot be included in the main JellyFin plugin repo. This plugin was sourced from the original Emby repo and sadly came without a license.

For updating, you will need to follow and download the releases that are published periodically (https://github.com/jesseward/jellyfin-plugin-lastfm/releases).
